import time
from pathlib import Path
import structlog
from mether.events.bus import EventBus
from mether.memory.persistent_memory import PersistentMemory

logger = structlog.get_logger(__name__)

class ExportAgent:
    """Export Agent: Compiles reports into PDF, DOCX, HTML, Markdown, and PowerPoint slide decks."""

    def __init__(self, db: PersistentMemory, bus: EventBus) -> None:
        self.db = db
        self.bus = bus

    async def export_report(self, task_id: str, template: str, format_type: str) -> str:
        # 1. Fetch task and sections
        task_res = await self.db._run_query("SELECT topic FROM research_tasks WHERE id = ?", task_id)
        topic = task_res[0]["topic"] if task_res else "Research Report"
        
        sections = await self.db._run_query(
            "SELECT title, validated_content, content FROM research_sections WHERE task_id = ? ORDER BY order_idx ASC",
            task_id
        )
        
        # 2. Fetch bibliography
        citations = await self.db._run_query(
            "SELECT DISTINCT source_url, title FROM citations WHERE task_id = ?",
            task_id
        )
        
        # 3. Create output directory
        out_dir = Path("c:/Users/mayan/Free_claude_codde/research_exports")
        out_dir.mkdir(parents=True, exist_ok=True)
        
        timestamp = int(time.time())
        clean_topic = "".join(c if c.isalnum() else "_" for c in topic)[:30]
        
        # 4. Generate bibliography appendix
        bib_md = "\n## References\n\n"
        if citations:
            for idx, cit in enumerate(citations):
                bib_md += f"[{idx + 1}] *{cit['title']}*. Available at: {cit['source_url']}\n"
        else:
            bib_md += "No sources cited.\n"

        # 5. Compile Markdown first
        full_markdown = f"# {topic}\n\n*Generated by METHER OS Flagship Research Pipeline on {time.strftime('%Y-%m-%d')}*\n\n"
        for sec in sections:
            content = sec["validated_content"] or sec["content"] or "Section draft missing."
            full_markdown += f"## {sec['title']}\n\n{content}\n\n"
        full_markdown += bib_md
        
        format_upper = format_type.upper()
        
        if format_upper == "MARKDOWN":
            file_path = out_dir / f"{clean_topic}_{timestamp}.md"
            file_path.write_text(full_markdown, encoding="utf-8")
            return str(file_path)
            
        elif format_upper == "HTML":
            file_path = out_dir / f"{clean_topic}_{timestamp}.html"
            html_content = self._compile_html(topic, full_markdown)
            file_path.write_text(html_content, encoding="utf-8")
            return str(file_path)
            
        elif format_upper == "DOCX":
            file_path = out_dir / f"{clean_topic}_{timestamp}.docx"
            try:
                import docx
                doc = docx.Document()
                doc.add_heading(topic, level=0)
                doc.add_paragraph(f"Generated by METHER OS on {time.strftime('%Y-%m-%d')}")
                
                for sec in sections:
                    doc.add_heading(sec["title"], level=1)
                    content = sec["validated_content"] or sec["content"] or ""
                    doc.add_paragraph(content)
                    
                doc.add_heading("References", level=1)
                for idx, cit in enumerate(citations):
                    doc.add_paragraph(f"[{idx + 1}] {cit['title']} - {cit['source_url']}")
                doc.save(str(file_path))
                return str(file_path)
            except ImportError:
                # Fallback to Markdown with message
                fallback_path = out_dir / f"{clean_topic}_{timestamp}_fallback.md"
                fallback_path.write_text(f"--- NOTE: python-docx not installed. Fallback to Markdown ---\n\n{full_markdown}", encoding="utf-8")
                return str(fallback_path)
                
        elif format_upper == "PPTX":
            file_path = out_dir / f"{clean_topic}_{timestamp}.pptx"
            try:
                import pptx
                prs = pptx.Presentation()
                
                # Title slide
                slide = prs.slides.add_slide(prs.slide_layouts[0])
                slide.shapes.title.text = topic
                slide.placeholders[1].text = f"Research Slide Deck\nMETHER OS Pipeline // {time.strftime('%Y-%m-%d')}"
                
                for sec in sections:
                    slide = prs.slides.add_slide(prs.slide_layouts[1])
                    slide.shapes.title.text = sec["title"]
                    # Extract 3 main bullets from content
                    content = sec["validated_content"] or sec["content"] or ""
                    bullets = [b.strip("-* ") for b in content.split("\n") if b.strip().startswith(("-", "*"))][:4]
                    if not bullets:
                        bullets = [content[:250] + "..."]
                    slide.placeholders[1].text = "\n".join(f"• {b}" for b in bullets)
                    
                prs.save(str(file_path))
                return str(file_path)
            except ImportError:
                fallback_path = out_dir / f"{clean_topic}_{timestamp}_slides_fallback.md"
                fallback_path.write_text(f"--- NOTE: python-pptx not installed. Fallback to Slide Markdown ---\n\n# Presentation: {topic}\n\n" + "\n".join(f"## Slide: {s['title']}" for s in sections), encoding="utf-8")
                return str(fallback_path)
                
        elif format_upper == "PDF":
            file_path = out_dir / f"{clean_topic}_{timestamp}.pdf"
            try:
                from reportlab.lib.pagesizes import letter
                from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
                from reportlab.lib.styles import getSampleStyleSheet
                
                doc = SimpleDocTemplate(str(file_path), pagesize=letter)
                styles = getSampleStyleSheet()
                story = [
                    Paragraph(topic, styles['Title']),
                    Spacer(1, 12),
                    Paragraph(f"Generated by METHER OS on {time.strftime('%Y-%m-%d')}", styles['Normal']),
                    Spacer(1, 24)
                ]
                
                for sec in sections:
                    story.append(Paragraph(sec["title"], styles['Heading1']))
                    story.append(Spacer(1, 8))
                    content = sec["validated_content"] or sec["content"] or ""
                    story.append(Paragraph(content.replace("\n", "<br/>"), styles['BodyText']))
                    story.append(Spacer(1, 12))
                    
                doc.build(story)
                return str(file_path)
            except ImportError:
                fallback_path = out_dir / f"{clean_topic}_{timestamp}_pdf_fallback.html"
                html_content = self._compile_html(topic, full_markdown)
                fallback_path.write_text(html_content, encoding="utf-8")
                return str(fallback_path)
                
        else:
            # Fallback to Markdown
            file_path = out_dir / f"{clean_topic}_{timestamp}.md"
            file_path.write_text(full_markdown, encoding="utf-8")
            return str(file_path)

    def _compile_html(self, title: str, markdown: str) -> str:
        # Convert Markdown basic symbols to HTML
        lines = markdown.split("\n")
        html_lines = []
        for line in lines:
            if line.startswith("# "):
                html_lines.append(f"<h1>{line[2:]}</h1>")
            elif line.startswith("## "):
                html_lines.append(f"<h2>{line[3:]}</h2>")
            elif line.startswith("### "):
                html_lines.append(f"<h3>{line[4:]}</h3>")
            elif line.startswith("- ") or line.startswith("* "):
                html_lines.append(f"<li>{line[2:]}</li>")
            elif line.strip() == "":
                html_lines.append("<br/>")
            else:
                html_lines.append(f"<p>{line}</p>")
                
        body = "\n".join(html_lines)
        
        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background-color: #0b0f19;
            color: #d1d5db;
            line-height: 1.6;
            max-width: 800px;
            margin: 40px auto;
            padding: 0 20px;
        }}
        h1 {{ color: #4cd7f6; border-bottom: 1px solid rgba(76,215,246,0.2); padding-bottom: 10px; }}
        h2 {{ color: #8b5cf6; margin-top: 30px; }}
        h3 {{ color: #10b981; }}
        a {{ color: #4cd7f6; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        p {{ margin-bottom: 16px; color: rgba(209, 213, 219, 0.85); }}
        li {{ margin-left: 20px; color: rgba(209, 213, 219, 0.85); }}
        br {{ margin-bottom: 10px; }}
    </style>
</head>
<body>
    {body}
</body>
</html>
"""
